"""Implementation of agent whose batch_run method takes in both a list of questions and a list of corpus."""

import logging
import re
import traceback

import pandas as pd
from phantom_eval._types import (
    ContentTextMessage,
    Conversation,
    LLMChatResponse,
    Message,
)
from phantom_eval.agents.common import get_all_evidence
from phantom_eval.llm import InferenceGenerationConfig, LLMChat
from phantom_eval.prompts import LLMPrompt

logger = logging.getLogger(__name__)


class CoTWikiAgent:
    def __init__(
        self,
        llm_prompt: LLMPrompt,
        cot_examples: str = "",
    ):
        self.llm_prompt = llm_prompt
        self.cot_examples = cot_examples
        self.agent_interactions: Conversation = Conversation(messages=[])

    def combine_evidence_and_question(self, evidence: str, question: str) -> str:
        return self.llm_prompt.get_prompt().format(
            evidence=evidence, examples=self.cot_examples, question=question
        )

    def _build_agent_prompt(self, question: str, corpus: pd.DataFrame) -> str:
        evidence = get_all_evidence(corpus)
        return self.combine_evidence_and_question(evidence, question)

    async def run(
        self,
        llm_chat: LLMChat,
        question: str,
        inf_gen_config: InferenceGenerationConfig,
        corpus: pd.DataFrame,
        parse_thinking_output: bool = False,
    ) -> LLMChatResponse:
        raise NotImplementedError("Not implemented")

    async def batch_run(
        self,
        llm_chat: LLMChat,
        questions: list[str],
        inf_gen_config: InferenceGenerationConfig,
        corpora: list[pd.DataFrame],
        parse_thinking_output: bool = False,
    ) -> list[LLMChatResponse]:
        """
        Args:
            llm_chat (LLMChat): LLM chat object
            questions (list[str]): List of questions
            inf_gen_config (InferenceGenerationConfig): Inference generation config
            corpora (list[pd.DataFrame]): List of same length as questions containing the corpus
                for each question.
            parse_thinking_output (bool): If True, correctly parse thinking output
                <think> ... </think> generated by LLMs like DeepSeek-R1.
                Set it to False for LLMs that do not generate <think> tags.
                Defaults to False.
        """
        logger.debug(f"\n\t>>> questions: {questions}\n")

        # Create a conversation for each user prompt, and initialize agent interactions
        prompts: list[str] = [
            self._build_agent_prompt(question, corpus) for question, corpus in zip(questions, corpora)
        ]
        convs = [
            Conversation(messages=[Message(role="user", content=[ContentTextMessage(text=prompt)])])
            for prompt in prompts
        ]
        self.agent_interactions = convs

        # Generate response
        inf_gen_config = inf_gen_config.model_copy(
            update=dict(stop_sequences=[]), deep=True
        )  # remove \n from stop sequences
        responses = await llm_chat.batch_generate_response(convs, inf_gen_config)

        # Add the responses to the agent's conversations
        for i, response in enumerate(responses):
            self.agent_interactions[i].messages.append(
                Message(role="assistant", content=[ContentTextMessage(text=response.pred)])
            )

        # Parse the responses to extract the answers
        parsed_responses: list[LLMChatResponse] = []
        for response in responses:
            # Try to parse the response, otherwise return an error
            try:
                if parse_thinking_output:
                    pred = CoTWikiAgent.parse_thinking_answer(response.pred)
                else:
                    pred = CoTWikiAgent.parse_answer(response.pred)
                error = None
            except Exception:
                pred = ""
                error = f"<agent_error>{traceback.format_exc()}</agent_error>"
            parsed_responses.append(LLMChatResponse(pred=pred, usage=response.usage, error=error))
        return parsed_responses

    @classmethod
    def parse_answer(cls, pred: str) -> str:
        """
        Parse the response to extract the answer using regex.
        The prediction should be of the form: "... The answer is <answer>." otherwise a ValueError is raised.
        """
        # NOTE: Allow for empty answer instead of throwing an error
        pattern = r"[tT]he answer is (.*)\.\s*$"
        m = re.search(pattern, pred)
        if m:
            return m.group(1)
        else:
            raise ValueError(f"Answer '{pred}' cannot be parsed.")

    @classmethod
    def parse_thinking_answer(cls, pred: str) -> str:
        """
        Parse the response to extract the answer using regex.
        The prediction should be of the form: "</think>... The answer is <answer>."
        otherwise a ValueError is raised.
        """
        # NOTE: Allow for empty answer instead of throwing an error
        pattern = r"</think>.*[tT]he answer is \s*(.*)\."
        m = re.search(pattern, pred, re.DOTALL)  # re.DOTALL to match newlines as well
        if m:
            return m.group(1)
        else:
            raise ValueError(f"Answer '{pred}' cannot be parsed.")

    def reset(self) -> None:
        self.agent_interactions: Conversation = Conversation(messages=[])
