# Script config
dataset_name: "data/wiki-v1-easy-no-agg"
split_list:
  [
    "depth_10_size_25_seed_11",
    "depth_10_size_25_seed_12",
    "depth_10_size_25_seed_13",
    "depth_10_size_25_seed_14",
    "depth_10_size_25_seed_15",
    "depth_10_size_25_seed_16",
    "depth_10_size_25_seed_17",
    "depth_10_size_25_seed_18",
    "depth_10_size_25_seed_19",
    "depth_10_size_25_seed_20",
  ]
from_local: true
eval_dataset_name: "data/wiki-v1-easy-no-agg"
eval_split_list: ["depth_10_size_25_seed_1"]
eval_from_local: true
data_curriculum: "random"

# Model arguments
model_name_or_path: "Qwen/Qwen2.5-1.5B-Instruct"
bf16: true
torch_dtype: bfloat16

# Trainer arguments
num_train_epochs: 3
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
packing: false
# size_25 universe is about 2500 tokens, so we set the max length to 4096
max_length: 4096

# Evaluation config
bf16_full_eval: true
# eval_on_start: true
eval_strategy: "steps"
eval_steps: 100
per_device_eval_batch_size: 8

# Logging config
log_level: "info"
logging_strategy: "steps"
logging_first_step: true
logging_steps: 50
save_strategy: "steps"
save_steps: 50
save_total_limit: 5
