#!/usr/bin/env bash
#SBATCH --job-name=sft-sol
#SBATCH --output=logs/sft-sol-%j.out
#SBATCH --error=logs/sft-sol-%j.err
#SBATCH -p ai
#SBATCH -N 1
#SBATCH -n 8
#SBATCH --gres=gpu:1
#SBATCH --mem=50GB
#SBATCH --time=24:00:00
#SBATCH --mail-user=ak2426@cornell.edu
#SBATCH --mail-type=all
#SBATCH -A nairr250102-ai
module load conda
source $(pwd)/scripts/anvil/load_modules_cuda.sh
# Set CONDA_ENV_NAME to default if not set
if [ -z "$CONDA_ENV_NAME" ]; then
    CONDA_ENV_NAME="phantom-reasoning"
fi
conda activate $CONDA_ENV_NAME

# First argument should be path to the accelerate config file
# Second argument should be the path to the training config file
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <path_to_accelerate_config> <path_to_config_file> [additional_args]"
    exit 1
fi
ACCELERATE_CONFIG_FILE_PATH=$1
SFT_CONFIG_FILE_PATH=$2

# Get NUM_GPUS from nvidia-smi. It repeats the number of GPUs a few times, take the first one.
NUM_GPUS=$(nvidia-smi --query-gpu=count --format=csv,noheader,nounits | head -n 1)
NUM_PROCESSES=$((NUM_GPUS))

# Get CUDA visible devices as 0,...,NUM_GPUS-1 (0 indexing)
CUDA_DEVICES_TRAINING=$(seq -s, 0 $((NUM_GPUS - 1)))

# Get additional arguments
shift 2
cmd_args=$@
echo "-------------------------------"
echo "Additional arguments: $cmd_args"
echo "-------------------------------"

echo "-------------------------------"
echo "Starting SFT on solutions training with"
echo "- accelerate config=$ACCELERATE_CONFIG_FILE_PATH"
echo "- training config=$SFT_CONFIG_FILE_PATH"
echo "- on GPUs $CUDA_DEVICES_TRAINING"
echo "-------------------------------"

CUDA_VISIBLE_DEVICES=$CUDA_DEVICES_TRAINING ACCELERATE_LOG_LEVEL=info accelerate launch \
    --num_processes=$NUM_PROCESSES \
    --config_file $ACCELERATE_CONFIG_FILE_PATH \
    src/phantom_reasoner/sft_on_solutions.py \
    --config $SFT_CONFIG_FILE_PATH \
    $cmd_args
