# Model arguments
model_name_or_path: qwen/qwen2.5-1.5b-instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Script arguments
dataset_name: out-v05-0222-filtered-f1-above-0.9
data_dir: /share/nikola/phantom-wiki/eval/out-v05-0222-filtered-f1-above-0.9
method: cot
split: depth_20_size_50_seed_1
# NOTE: model_name is used to filter by the model name in the predictions
model_name: deepseek-ai/deepseek-r1-distill-qwen-32b

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: qwen2.5-1.5b-instruct-PR-distill
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: data/qwen2.5-1.5b-instruct-PR-distill
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
push_to_hub: false
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1